### ISSUE TITLE
An Issue when retrieving statements

### ISSUE THREAD

**Issue by JZeravik** [MatthiWare/FinancialModelingPrep.NET#80]
Hi, getting a deserialization ERROR when retrieving financial statements for many tickers, this was for ticker MTG.

ERROR when retrieving data for symbol: MTG message: System.Text.Json.JsonException: The JSON value could not be converted to System.Double. Path: $[0].interestIncome | LineNumber: 21 | BytePositionInLine: 26.
 ---> System.InvalidOperationException: **Cannot get the value of a token type 'Null' as a number.**
   at System.Text.Json.Utf8JsonReader.TryGetDouble(Double& value)
   at System.Text.Json.Utf8JsonReader.GetDouble()
   at System.Text.Json.Serialization.Converters.DoubleConverter.ReadNumberWithCustomHandling(Utf8JsonReader& reader, JsonNumberHandling handling, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

May I ask you to fix this serialization ERROR?
Thank you

**Comment by Matthiee** [comment]
Fixed in [v0.2.1](https://www.nuget.org/packages/MatthiWare.FinancialModelingPrep/0.2.1)

**Comment by JZeravik** [comment]
Thanks a lot, unfortunately the same fix is needed for more properties :(
